# Generated by Django 4.1.3 on 2024-05-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babyincubator', '0002_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='babys',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='babyincubator.parents'),
        ),
    ]
